### ISSUE TITLE
Create a github hosted static webpage about this project

### ISSUE THREAD

**Issue by chrismcafee** [spring2885/spring2885.github.io#1]
video: https://pages.github.com/

**Comment by chrismcafee** [comment]
Deleting `CNAME` in `spring2885.github.io/` will undo redirect

**Comment by chrismcafee** [comment]
Can create a sub dir within `artifacts/`  for wireframes as it's a `spring2885` private repo. Conversely, you'll want to add your public `img/` folder in `spring2885.github.io/` for src references in `index.html`. cc @laurahaddad

**Comment by chrismcafee** [comment]
**_CONTENT_**

**1.) About** Who is this site for and what does it do? Include some _HOWTO_ & basic use cases. See `artifacts/usecase/` for workflow notes.

**2.) Security** [prod and staging servers should redirect to HTTPS #225](https://github.com/spring2885/backend/issues/225)

**3.) Frontend** `frontend/README.md` section 4 titled _Current Packages Installed_

**4.) Backend** (REST + Server Side Java + Database) [NDNU Community Access API](http://www.spring-2885.org/api-docs/index.html)

**5.) Testing** `org.mockito.Mockito.*` `org.springframework.test.web.servlet.*` `org.junit.Test`

**6.) Production** `production/setup/README.md` installing `Docker`, running `Containers`, and configuring `MySQL`. 

**7.) Contributors** [https://github.com/orgs/spring2885/people](https://github.com/orgs/spring2885/people) 

**8.) NEW FEATURES** This will be the material we present in May. Ambitiously speaking, it'll include: `newsfeed advanced search`, `database restructuring by department/major`, `social sign-in`, `password reset`, `multi lang support`, `Bootstrap cards`, `HTTPS redirect`, `metrics export`

**Comment by chrismcafee** [comment]
Progress on this?

**Comment by bbez1** [comment]
Laura has created a template and in class she had pushed to her github and submitted a pull request. I am going to work on helping to populate the page with content and make a few tweaks. Did you see the pull request come through?

Thanks Chris!

**Comment by chrismcafee** [comment]
no

**Comment by chrismcafee** [comment]
upload commit: 93d5917a9e8ad7221a153d810e346f3e8f58851a
merge conflict resolution: 8db017a125c10c272efed38fb0a2742638015f44

closing issue as merge conflicts resolved.

@laurahaddad @bbez1 ~ please feel free to open subsequent iss# in this repo for collaboration on your next milestone/task
